apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 533267351303.dkr.ecr.us-east-1.amazonaws.com/mysql
        ports:
        - containerPort: 3306
